version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo69
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: schoolmongo
    ports:
      - "27017:27017"
    command: --auth

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongo

  postgres:
    image: postgres:14-alpine
    container_name: school_db
    environment:
      POSTGRES_USER: school
      POSTGRES_PASSWORD: root
      POSTGRES_DB: school
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: school@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  app:
    image: dockermirea/digital-api:1.0
    container_name: app
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/school
      POSTGRES_USERNAME: school
      POSTGRES_PASSWORD: root
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: mongo
      MONGO_PASSWORD: root
      MONGO_DATABASE: schoolmongo
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - mongo-express
      - pgadmin
      - postgres

